config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
	root 'static_pages#home'
  get "/fetch_posts" => 'static_pages#filter_posts', as: 'fetch_posts'
  get "/fetch_category_posts" => 'categories#filter_posts', as: 'fetch_category_posts'
  get "/fetch_categories" => 'categories#order_categories', as: 'fetch_categories'
  get "/c/all" => 'categories#all' #pseudocategory
  get 'search' => 'static_pages#search'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'error_404' => 'static_pages#not_found'
  get 'sitemap.xml', :to => 'static_pages#sitemap', :defaults => {:format => 'xml'}
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :followings, only: [:create, :destroy]
  resources :users do
    member do
      get :categories
    end
  end
  resources :categories, :path => 'c' # e.g. localhost:3000/c/shirts
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :posts, only: [:new, :show, :create, :destroy] do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
    resources :comments
  end
  
  get "*any", via: :all, to: "static_pages#not_found" # path error handling
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: { maximum: 248 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :upvote, :downvote]
  before_action :correct_user, only: [:destroy]
  before_action :commenting_too_much, only: [:create]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      @comment.upvote_by current_user
      flash[:success] = "Comment created"
      redirect_to :back
      #respond_to do |format|
      #  format.html {redirect_to :back }
      #  format.js
      #end
    else
      flash[:danger] = "Comment cannot be blank"
      redirect_to :back
    end
  end

  def destroy
    @comment.destroy
    
    respond_to do |format|
      format.html {redirect_to :back }
      format.js
    end
  end

  def upvote
      @comment = Comment.find(params[:id])
      # if already upvoted and button got clicked, unupvote and remove stylepoint
      if current_user.voted_up_on? @comment
        @comment.unliked_by current_user
        #@comment.user.decrease_stylepoints if @post.user != current_user
        respond_to do |format|
          format.html {redirect_to :back }
          format.js { render 'unvote.js.erb' }
        end
      else
        @comment.upvote_by current_user
        #@comment.user.increase_stylepoints if @post.user != current_user
        respond_to do |format|
          format.html {redirect_to :back }
          format.js
        end
      end
  end

  def downvote
      @comment = Comment.find(params[:id])
      # if already downvoted and button got clicked, undownvote and give post.user back stylepoint
      if current_user.voted_down_on? @comment
        @comment.undisliked_by current_user
        #@comment.user.increase_stylepoints if @post.user != current_user
        respond_to do |format|
          format.html {redirect_to :back }
          format.js { render 'unvote.js.erb' }
        end
      else
        @comment.downvote_by current_user
        #@comment.user.decrease_stylepoints if @post.user != current_user
        respond_to do |format|
          format.html {redirect_to :back }
          format.js
        end
      end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body, :user_id)
    end

    def correct_user
      @comment = Comment.find(params[:id])
      redirect_to root_url unless @comment.user = current_user || current_user.admin?
    end

    def commenting_too_much
      comments_per_hour = 10
      if current_user.comments.where('created_at > ?', 5.minutes.ago).count >= comments_per_hour && !current_user.admin?
        flash[:danger] = "You're commenting too much."
        redirect_to :back
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
	
	<div class="comment_wrapper row">	

		<div class="voting-wrapper col-xs-2">
			<div class="voting pull-right">	
				<span id="comment-<%= comment.id %>-score"><%= comment.cached_votes_score %></span>
				<span class="btn-group-vertical">
					<% active_css = logged_in? && current_user?(current_user) && current_user.voted_up_on?(comment) ? "active" : "" %>
					<% use_ajax = logged_in? %>
			    <%= link_to upvote_comment_path(comment), method: :put, remote: use_ajax, id: "upvote-comment-" + comment.id.to_s + "-button", class: "btn btn-sm btn-upvote #{active_css}" do %>
			    	<i class="fa fa-arrow-up" aria-hidden="true"></i>
			    <% end %>
			    <% active_css = logged_in? && current_user?(current_user) && current_user.voted_down_on?(comment) ? "active" : "" %>
			    <%= link_to downvote_comment_path(comment), method: :put, remote: use_ajax, id: "downvote-comment-" + comment.id.to_s + "-button", class: "btn btn-sm btn-downvote #{active_css}" do %>
			    	<i class="fa fa-arrow-down" aria-hidden="true"></i>
			    <% end %>
			  </span>
			</div>
		</div>

		<div class="comment-body col-xs-9">

			<% if current_user?(comment.user) || (logged_in? && current_user.admin?)%>
				<div title="delete comment?" class="btn-group delete-button">
					<%= link_to comment, method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: "btn btn-ominous btn-xs" do %>
						<i class="fa fa-times" aria-hidden="true"></i>
					<% end %>
				</div>
			<% end %>

			

			<span class="comment">
				<% class_name = comment.user == comment.post.user ? "op_user" : "" %>
				<span><%= link_to comment.user.username, comment.user, class: "#{class_name}" %> | <small><%= time_ago_in_words(comment.created_at) %></small></span>
				<p><%= comment.body %></p>
			</span>

		</div>

	</div>



</li>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$(".comments").prepend("<%= escape_javascript(render :partial => 'comment', :locals => { :comment => @comment } ) %>");

$('#comment-<%= @comment.id %>').effect("highlight", {}, 1000);

$('#comment_body').val('')

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").hide('slow', function (){

	$(this).parentElement.removeChild($(this));
});

app/views/comments/downvote.js.erb
$('#upvote-comment-<%= @comment.id %>-button').removeClass('active');
$('#downvote-comment-<%= @comment.id %>-button').addClass('active');
$('#comment-<%= @comment.id %>-score').html('<%= @comment.cached_votes_score %>')

app/views/comments/unvote.js.erb
$('#downvote-comment-<%= @comment.id %>-button').removeClass('active').blur();
$('#upvote-comment-<%= @comment.id %>-button').removeClass('active').blur();
$('#comment-<%= @comment.id %>-score').html('<%= @comment.cached_votes_score %>')

app/views/comments/upvote.js.erb
$('#downvote-comment-<%= @comment.id %>-button').removeClass('active');
$('#upvote-comment-<%= @comment.id %>-button').addClass('active');
$('#comment-<%= @comment.id %>-score').html('<%= @comment.cached_votes_score %>')