config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
	root 'static_pages#home'
  get "/fetch_posts" => 'static_pages#filter_posts', as: 'fetch_posts'
  get "/fetch_category_posts" => 'categories#filter_posts', as: 'fetch_category_posts'
  get "/fetch_categories" => 'categories#order_categories', as: 'fetch_categories'
  get "/c/all" => 'categories#all' #pseudocategory
  get 'search' => 'static_pages#search'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'error_404' => 'static_pages#not_found'
  get 'sitemap.xml', :to => 'static_pages#sitemap', :defaults => {:format => 'xml'}
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :followings, only: [:create, :destroy]
  resources :users do
    member do
      get :categories
    end
  end
  resources :categories, :path => 'c' # e.g. localhost:3000/c/shirts
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :posts, only: [:new, :show, :create, :destroy] do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
    resources :comments
  end
  
  get "*any", via: :all, to: "static_pages#not_found" # path error handling
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :category
  default_scope -> { highest_score }#order(created_at: :desc) }
  validates :user_id, presence: true
  validates :category_id, presence: { message: "missing. Please assign an existing category." }
  validates :image_link, presence: true, length: { maximum: 2048 }
  validates :buy_link, presence: true, length: { maximum: 2048 }

  def self.highest_score
  	self.order(:cached_votes_score => :desc).order(:created_at => :desc)	
  end

  def self.search(search)
    where("lower(image_link) like ? or lower(buy_link) like ?", "%#{search}%".downcase, "%#{search}%".downcase)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy, :upvote, :downvote]
	before_action :correct_user,   only: :destroy
	before_action :posting_too_much, only: :create

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
				@post.upvote_by current_user
				flash[:success] = "Post created."
				redirect_to root_url
		else
			render 'new'
		end
	end

	def show
  	@post = Post.find(params[:id])
    @comments = @post.comments.order(cached_votes_score: :desc).order(created_at: :desc).all
  end

	def destroy
		@post.destroy
    #flash[:success] = "Post deleted"
    respond_to do |format|
	    format.html {redirect_to current_user }
	    format.js
	  end
	end

	def upvote
			@post = Post.find(params[:id])
			# if already upvoted and button got clicked, unupvote and remove stylepoint
			if current_user.voted_up_on? @post
				@post.unliked_by current_user
				@post.user.decrease_stylepoints if @post.user != current_user
				respond_to do |format|
			    format.html {redirect_to :back }
			    format.js { render 'unvote.js.erb' }
			  end
			else
				@post.upvote_by current_user
				@post.user.increase_stylepoints if @post.user != current_user
				respond_to do |format|
			    format.html {redirect_to :back }
			    format.js
			  end
			end
	end

	def downvote
			@post = Post.find(params[:id])
			# if already downvoted and button got clicked, undownvote and give post.user back stylepoint
			if current_user.voted_down_on? @post
				@post.undisliked_by current_user
				@post.user.increase_stylepoints if @post.user != current_user
				respond_to do |format|
			    format.html {redirect_to :back }
			    format.js { render 'unvote.js.erb' }
			  end
			else
				@post.downvote_by current_user
				@post.user.decrease_stylepoints if @post.user != current_user
				respond_to do |format|
			    format.html {redirect_to :back }
			    format.js
			  end
			end
	end

	private

		def post_params
      params.require(:post).permit(:image_link, :buy_link, :category_id)
    end

     def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      if @post.nil? && current_user.admin?
      	@post = Post.find(params[:id])
      end

      redirect_to root_url if @post.nil?
    end

    def posting_too_much
    	posts_per_hour = 5
    	if current_user.posts.where('created_at > ?', 1.hour.ago).count >= posts_per_hour && !current_user.admin?
    		flash[:danger] = "You're posting too much. Five posts per hour are allowed."
    		redirect_to new_post_path
    	end
    end

end

app/helpers/posts_helper.rb
module PostsHelper

	# Returns the full title on a per-page basis.
  def full_url(my_url = '')
    if !my_url.include?('http')
      'http://' + my_url
    #	'https://' + my_url
    #elsif !my_url.include?('https') && my_url.include?('http')
    #	my_url.sub('http','https')
    else
    	my_url
    end
  end

end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>" class="col-md-3">
  <div class="post-container">
    <% if logged_in? && (post.user.id == current_user.id || current_user.admin?) %>
      <div title="delete post?" class="btn-group delete-button">
        <%= link_to post, method: :delete, data: {confirm: "Are you sure?"}, remote: true, class: "btn btn-ominous btn-xs" do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      </div>
    <% end %>
    <div class="post-image-container">
    <div class="image_link"><%= link_to image_tag(full_url(post.image_link)), full_url(post.buy_link), target: '_blank' %></div>
    </div>
    <div class="post-details-container">
    
    <div class="row">

      <span class="voting col-xs-4">
      	<div title="vote on this post" class="btn-group-vertical">
    	    <% active_css = logged_in? && current_user?(current_user) && current_user.voted_up_on?(post) ? "active" : "" %>
          <% use_ajax = logged_in? %>
          <%= link_to upvote_post_path(post), method: :put, remote: use_ajax, id: "upvote-" + post.id.to_s + "-button", class: "btn btn-xs btn-upvote #{active_css}" do %>
    	    	<i class="fa fa-arrow-up" aria-hidden="true"></i>
    	    <% end %>
          <% active_css = logged_in? && current_user?(current_user) && current_user.voted_down_on?(post) ? "active" : "" %>
    	    <%= link_to downvote_post_path(post), method: :put, remote: use_ajax, id: "downvote-" + post.id.to_s + "-button", class: "btn btn-xs btn-downvote #{active_css}" do %>
    	    	<i class="fa fa-arrow-down" aria-hidden="true"></i>
    	    <% end %>
        </div>
        <span id="post-<%= post.id %>-score"><%= post.cached_votes_score %></span>
      </span>

      <span class="category col-xs-8"><%= link_to post.category.name, post.category, class: "pull-right" %></span><br>
    </div>

    <div class="row">
      <span class="comment_count col-xs-6"><%= link_to "#{post.comments.count} Comments", post %></span>
    </div>
    
    <span class="post_footer">
      <span class="timestamp">Posted <%= time_ago_in_words(post.created_at) %> ago by </span>
      <span title='<%= "#{post.user.username}: #{pluralize(post.user.stylepoints, 'stylepoint')}" %>' 
            class="user"><%= link_to post.user.username, post.user %></span>.
    </span>
    </div>
  </div>
</li>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <p>
      <small>
        Right click an image on a website and copy the image address to get an image link.
      </small>
    </p>
    <%= f.label "link to image" %>
    <%= f.text_field :image_link, placeholder: "Link to an image...", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "link to store" %>
    <%= f.text_field :buy_link, placeholder: "Link to where I can buy this...", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "category" %>
    <%= #f.select :category_id, options_from_collection_for_select(@categories,'id', 'name'), :prompt => "Select one" 
    %>
    <input id="select_category" , class="form-control" placeholder="Which category does this belong to..."/>
    <input id="post_category_id" name="post[category_id]" type="hidden"/>
  </div>
  <%= f.submit "Post", class: "btn btn-cool" %>
<% end %>

<script type="text/javascript">

$(function() {
 
  $('#select_category').autocomplete({
      minLength: 2,
      source: '<%= categories_path(:json) %>',
      autoFocus: true,
      select: function(event, ui) {
          $('#select_category').val(ui.item.name);
          $("#post_category_id").val(ui.item.id);
          return false;
      }
  })
  .data( "uiAutocomplete" )._renderItem = function( ul, item ) {
      return $( "<li></li>" )
          .data( "item.autocomplete", item )
          .append( "<a>" + item.name + "</a>" )
          .appendTo( ul );
  };


}); 




</script>

app/views/posts/destroy.js.erb
$("#post-<%= @post.id %>").hide('slow', function (){

	$(this).parentElement.removeChild($(this));
});

app/views/posts/downvote.js.erb
$('#upvote-<%= @post.id %>-button').removeClass('active');
$('#downvote-<%= @post.id %>-button').addClass('active');
$('#post-<%= @post.id %>-score').html('<%= @post.cached_votes_score %>')

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>
<% provide(:button_text, 'Post it!') %>
<h1>New Post</h1>

<div class="row">
  <div class="col-md-6">
    <%= render 'post_form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="page-header">
	<h1 style="text-align:center"><small>submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= link_to @post.user.username, @post.user %></small></h1>
</div>
<div class="post_show_page_container">
	<span class="voting">	
		<div class="btn-group-vertical">
			<% active_css = logged_in? && current_user?(current_user) && current_user.voted_up_on?(@post) ? "active" : "" %>
			<% use_ajax = logged_in? %>
	    <%= link_to upvote_post_path(@post), method: :put, remote: use_ajax, id: "upvote-" + @post.id.to_s + "-button", class: "btn btn-sm btn-upvote #{active_css}" do %>
	    	<i class="fa fa-arrow-up" aria-hidden="true"></i>
	    <% end %>
	    <% active_css = logged_in? && current_user?(current_user) && current_user.voted_down_on?(@post) ? "active" : "" %>
	    <%= link_to downvote_post_path(@post), method: :put, remote: use_ajax, id: "downvote-" + @post.id.to_s + "-button", class: "btn btn-sm btn-downvote #{active_css}" do %>
	    	<i class="fa fa-arrow-down" aria-hidden="true"></i>
	    <% end %>
	  </div>
	  <span id="post-<%= @post.id %>-score"><%= @post.cached_votes_score %></span>
	</span>

	<% if current_user?(@post.user) || (logged_in? && current_user.admin?) %>
		<div class="btn-group pull-right" title="delete post?">
			<%= link_to 'Delete', @post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-ominous" %>
		</div>
	<% end %>

	<div class="image_link_show_page"><%= image_tag(full_url(@post.image_link)) %></div>

	<span class="buy_link pull-right"><%= link_to "check it out", full_url(@post.buy_link), target: '_blank' %></span>

	<span class="category"><%= link_to @post.category.name, @post.category %></span>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h3 class="comments_title"><%= @post.comments.count %> Comments</h3>

		<% if logged_in? %>
				<%= form_for [@post, @post.comments.build] do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<div class="field">
					<%= f.text_area :body, class: 'form-control' %>
				</div>
				<%= f.submit "Comment", class: "btn btn-cool" %>

				<% end %>
		<% end %>
	</div>
</div>
<div class="row">
		<div id="comments">
				<%= render 'shared/comments' %>
		</div>
</div>

<script>
	$(function(){
		
		$('.op_user').prop('title', 'original poster');

	});
</script>

app/views/posts/unvote.js.erb
$('#downvote-<%= @post.id %>-button').removeClass('active').blur();
$('#upvote-<%= @post.id %>-button').removeClass('active').blur();
$('#post-<%= @post.id %>-score').html('<%= @post.cached_votes_score %>')

app/views/posts/upvote.js.erb
$('#downvote-<%= @post.id %>-button').removeClass('active');
$('#upvote-<%= @post.id %>-button').addClass('active');
$('#post-<%= @post.id %>-score').html('<%= @post.cached_votes_score %>')