config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
	root 'static_pages#home'
  get "/fetch_posts" => 'static_pages#filter_posts', as: 'fetch_posts'
  get "/fetch_category_posts" => 'categories#filter_posts', as: 'fetch_category_posts'
  get "/fetch_categories" => 'categories#order_categories', as: 'fetch_categories'
  get "/c/all" => 'categories#all' #pseudocategory
  get 'search' => 'static_pages#search'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'error_404' => 'static_pages#not_found'
  get 'sitemap.xml', :to => 'static_pages#sitemap', :defaults => {:format => 'xml'}
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :followings, only: [:create, :destroy]
  resources :users do
    member do
      get :categories
    end
  end
  resources :categories, :path => 'c' # e.g. localhost:3000/c/shirts
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :posts, only: [:new, :show, :create, :destroy] do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
    resources :comments
  end
  
  get "*any", via: :all, to: "static_pages#not_found" # path error handling
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :followings, foreign_key: :category_id, dependent: :destroy
	has_many :users, through: :followings 
	validates :name, uniqueness: true, presence: true,
										length: { maximum: 20 }
	VALID_CATEGORY_REGEX = /\A[A-Za-z0-9-]+\z/
	validates :slug, uniqueness: true, presence: true, format: { with: VALID_CATEGORY_REGEX,
																message: ' must only include letters, numbers, and hyphens'},
										length: { maximum: 20 }, exclusion: { in: ['new','all']}
	validates :description, length: { maximum: 64 }

	def to_param
		slug
	end

	def self.search(search)
    where("lower(name) like ? or lower(slug) like ? or lower(description) like ?", 
    	"%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
	before_action :admin_user,     only: [:edit, :update, :destroy]
	before_action :find_category, only: [:show, :edit, :update, :destroy, :filter_posts]
  before_action :creating_too_much, only: :create

	def new 
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
    @category.user_id = current_user.id
    if @category.save
    	flash[:success] = "Category created."
      redirect_to categories_path
    else
      render 'new'
    end
	end

	def edit

	end

	def update
		if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to categories_path
    else
      render 'edit'
    end
	end

	def destroy
		@category.destroy
    flash[:success] = "Category deleted"
    redirect_to categories_path
	end

	def index
    @category_order = session[:category_order] || '1'
    if params[:term]
      @categories = Category.where('lower(name) like ?', "%#{params[:term].downcase}%")
    else
  		@categories = order_by_selection(@category_order).paginate(page: params[:page])
      #Category.all.order(:name).paginate(page: params[:page])
    end

    respond_to do |format|
      format.html

      format.json { render :json => @categories.to_json }
    end
	end

	def show
		@date_filter = session[:date_filter] || '5'
  	#@category = Category.find_by(slug: params[:slug])
    @posts = @category.posts.all
    @posts = filter_by_date(@date_filter).paginate(page: params[:page], per_page: 32)
  end

  def all # acts as a pseudocategory
    @date_filter = session[:date_filter] || '5'
    @posts = Post.all
    @feed_items = filter_by_date(@date_filter).paginate(page: params[:page], per_page: 32)
    render 'all'
  end

  def order_categories
    @category_order = params[:category_order]
    session[:category_order] =  @category_order
    @categories = order_by_selection(@category_order).paginate(page: params[:page])

    respond_to do |format|
        format.html {redirect_to :back }
        format.js
    end
  end

  def filter_posts
  	
    @date_filter = params[:date_filter]
    session[:date_filter] =  @date_filter

    @posts = @category.posts.all
    @posts = filter_by_date(@date_filter).paginate(page: params[:page])

    respond_to do |format|
        format.html {redirect_to :back }
        format.js
    end
  end

	private

    def category_params
      if current_user.admin?
        params.require(:category).permit(:name, :slug, :description, :is_default)
      else
        params.require(:category).permit(:name, :slug, :description)
      end
    end    

    def find_category
    	@category = Category.find_by_slug!(params[:id])
    end

    def order_by_selection(category_order)
      case category_order
        when '1' #name
          @categories = Category.all.order('name ASC')
        when '2' #follower count
          @categories = Category.all.order('users_count DESC').order('name ASC')
        else
          @categories = Category.all.order('name ASC')
      end
    end

    def filter_by_date(date_filter)
      case date_filter
        when '1' #day
          @posts.where(:created_at => 1.day.ago..Time.now)
        when '2' #week
          @posts.where(:created_at => 7.day.ago..Time.now)
        when '3' #month
          @posts.where(:created_at => 31.day.ago..Time.now)
        when '4' #year
          @posts.where(:created_at => 365.day.ago..Time.now)
        when '5' #all time
          @posts
        when '6' #newest
          @posts.reorder('created_at DESC')
        else
          @posts.where(:created_at => 1.day.ago..Time.now)
      end
    end

    def creating_too_much
      categories_per_period = 2
      if Category.where('user_id = ? and created_at > ?', current_user.id, 15.minutes.ago).count >= categories_per_period && !current_user.admin?
        flash[:danger] = "You're creating categories too much. Two categories per 15 minutes are allowed."
        redirect_to new_category_path
      end
    end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li>

  <% if logged_in? %>
    <span class="follow_form pull-left" id="follow_form_<%= category.id %>">
      <% @category = category %>
      <% if current_user.following?(category) %>
        <%= render 'categories/unfollow' %>
      <% else %>
        <%= render 'categories/follow' %>
      <% end %>
    </span>
  <% end %>

  <span class="category_name"><%= link_to category.name, category %></span>

  <% if category.is_default? %>
    <span style="font-size:.8em;padding:3px;color:red;border: 2px solid red;border-radius:3px;">Default</span>
  <% end %>

  <br>

  <span class="category_description"><i><span id="follower-count-<%= category.id %>"><%= category.users_count %></span> followers</i>. <%= category.description %></span>

  <% if logged_in? && current_user.admin? %>
    <%= link_to category, method: :delete, data: { confirm: "Are you sure?" },class: "btn btn-xs btn-ominous pull-right" do %>
      <i class="fa fa-times" aria-hidden="true"></i>
    <% end %>
    <%= link_to "edit", edit_category_path(category), class: "btn btn-xs btn-cool pull-right", style: "margin: 0px 5px;" %>
  <% end %>
</li>

app/views/categories/_category_list.html.erb
<% if @categories.any? %>
    <%= will_paginate %>

		<ul class="categories">
			<li>
			  <span class="category_name"><%= link_to "All", c_all_path %></span><br>
			  <span class="category_description">Every category in one place.</span>
			</li>
		  <%= render @categories %>
		</ul>

		<%= will_paginate %>
<% end %>

app/views/categories/_feed.html.erb
<% if @posts.any? %>
    <ol class="posts">
      <%= render @posts %>
    </ol>
    <%= will_paginate @posts %>
  <% end %>

app/views/categories/_follow.html.erb
<%= form_for(current_user.followings.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :category_id, @category.id %></div>
  <%= f.submit "Follow", class: "btn btn-cool btn-xs" %>
<% end %>

app/views/categories/_unfollow.html.erb
<%= form_for(current_user.followings.find_by(category_id: @category.id),
           html: { method: :delete }, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn btn-warm btn-xs" %>
<% end %>

app/views/categories/all.html.erb
<div class="row">
  <span class="col-sm-8"><h1>All Posts</h1></span>
  <span id="filter_label" class="col-sm-2">
    <%= label_tag 'Filter:', nil, class:"pull-right"   %>
  </span>
  <span id="date_filter_form_wrapper" class="col-sm-2">
  	<%= form_tag(fetch_posts_path, method: :get, remote: true, id: "date_filter_form") do %>
    	<div class="field">
    	<%= select_tag(:date_filter, 
    			options_for_select([['Day', 1], ['Week', 2], ['Month',3], ['Year',4], ['All Time',5], ['Newest',6]], @date_filter), 
    													onchange: "$(this.form).submit();", 
    													class: "form-control" ) %>
    	
    	</div>
  	<% end %>
  </span>
</div>
<div class="row" id="home_feed">
    <%= render 'shared/feed' %>
</div>

app/views/categories/edit.html.erb
<% provide(:title, "Edit category") %>
<h1>Update Category</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@category) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>

		  <%= f.label :name %>
		  <%= f.text_field :name, class: 'form-control' %>

		  <%= f.label :slug %>
		  <div class="input-group form-group">
		  	<span class="input-group-addon"><i>/c/</i></span><%= f.text_field :slug, class: 'form-control' %>
		  </div>

		  <%= f.label :description %>
		  <%= f.text_area :description, class: 'form-control' %>

		  <%= f.label :is_default, :class => "checkbox" do %>
		  Default<%= f.check_box :is_default, :style => "vertical-align:middle;width:20%;" %>
		  <% end %>

		  <%= f.submit "Save Changes", class: "btn btn-cool" %>
		<% end %>
  </div>
</div>

app/views/categories/filter_posts.js.erb
$("#category_feed").html("<%= escape_javascript(render 'feed') %>"); 

app/views/categories/index.html.erb
<% provide(:title, 'Categories') %>
<h1>Categories</h1>

<div class="row">
	<span class="col-md-7">
		<%= link_to "Create new Category", new_category_path, class: "btn btn-cool" %>
	</span>
	<span id="order_dropdown" class="col-sm-2 pull-right">	
	  <%= form_tag(fetch_categories_path, method: :get, remote: true, id: "order_categories_form") do %>
	    
	    <div class="field">
	    	<%= select_tag(:category_order, 
	    			options_for_select([['Name', 1], ['# Followers', 2]], @category_order), 
	    													onchange: "$(this.form).submit();", 
	    													class: "form-control" ) %>
	    	
	  	</div>
		<% end %>
	</span>
	<span id="order_label" class="col-sm-3 pull-right">
		<%= label_tag 'Order by:', nil, class:"pull-right"   %>
	</span>
</div>

<div id="category_list">
	<%= render 'category_list' %>
</div>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<h1>New Category</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for(@category) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>

	  <%= f.label :name %>
	  <%= f.text_field :name, class: 'form-control' %>

	  <%= f.label :slug %>
	  <div class="input-group form-group">
	  	<span class="input-group-addon"><i>/c/</i></span><%= f.text_field :slug, class: 'form-control' %>
	  </div>

	  <%= f.label :description %>
	  <%= f.text_area :description, class: 'form-control' %>

	  <% if logged_in? && current_user.admin? %>
		  <%= f.label :is_default, :class => "checkbox" do %>
			  Default<%= f.check_box :is_default, id: "category_default_checkbox" %>
			  <% end %>
		<% end %>

	  <%= f.submit "Create", class: "btn btn-cool" %>
	  <span style="color:red">You will not be able to edit this category after it is created.</span>
	<% end %>
  </div>
</div>

app/views/categories/order_categories.js.erb
$("#category_list").html("<%= escape_javascript(render 'category_list') %>"); 

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<% provide(:meta_description, "Category: " + @category.name + " - " + @category.description) %>

<div class="row">
  <span class="col-sm-8 category_info"><h1><%= @category.name %></h1></span>
  <span id="filter_label" class="col-sm-2">
    <%= label_tag 'Filter:', nil, class:"pull-right"   %>
  </span>
  <span id="date_filter_form_wrapper" class="col-sm-2">
  	<%= form_tag(fetch_category_posts_path, method: :get, remote: true, id: "date_filter_form") do %>
    	<div class="field">
    	<%= select_tag(:date_filter, 
    			options_for_select([['Day', 1], ['Week', 2], ['Month',3], ['Year',4], ['All Time',5], ['Newest',6]], @date_filter),
    													onchange: "$(this.form).submit();", 
    													class: "form-control" ) %>
    	
    	</div>
      <%= hidden_field_tag :id, @category.slug %>
  	<% end %>
  </span>
</div>
<div class="row" id="category_feed">
  <%= render 'feed' %>
</div>