config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'users/new'
	root 'static_pages#home'
  get "/fetch_posts" => 'static_pages#filter_posts', as: 'fetch_posts'
  get "/fetch_category_posts" => 'categories#filter_posts', as: 'fetch_category_posts'
  get "/fetch_categories" => 'categories#order_categories', as: 'fetch_categories'
  get "/c/all" => 'categories#all' #pseudocategory
  get 'search' => 'static_pages#search'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'error_404' => 'static_pages#not_found'
  get 'sitemap.xml', :to => 'static_pages#sitemap', :defaults => {:format => 'xml'}
  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :followings, only: [:create, :destroy]
  resources :users do
    member do
      get :categories
    end
  end
  resources :categories, :path => 'c' # e.g. localhost:3000/c/shirts
  resources :comments do
    member do
      put "upvote", to: "comments#upvote"
      put "downvote", to: "comments#downvote"
    end
  end
  resources :posts, only: [:new, :show, :create, :destroy] do
    member do
      put "upvote", to: "posts#upvote"
      put "downvote", to: "posts#downvote"
    end
    resources :comments
  end
  
  get "*any", via: :all, to: "static_pages#not_found" # path error handling
end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>" id="flash"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Favowear <%= Time.now.strftime("%Y") %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <nav>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <i class="fa fa-bars fa-2x" id="nav-toggle-button" aria-hidden="true"></i>                       
      </button>
      <%= link_to image_tag("favicon-32x32.png"), root_path, id: "logoimage", class: "navbar-brand" %>
      <%= link_to "Favowear", root_path, id: "logo" %>
      <%= form_tag search_path, :method => 'get', class: 'input-group navbar-left', id: 'search_form'  do %>
        <%= text_field_tag :search, params[:search], required: true, class: 'form-control', maxlength: 128, placeholder: 'Search Favowear' %>
          <span class="input-group-btn">
          <%= button_tag type: 'submit', class: "btn btn-default", name: "", id: "search_button" do %>
            <!--<span class="glyphicon glyphicon-search"></span>-->
            <i class="fa fa-search" aria-hidden="true"></i>
          <% end %>
          </span>
      <% end %>
    </div>
      <div class="collapse navbar-collapse" id="myNavbar">

      

        <ul class="nav navbar-nav navbar-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to root_path do %><i class="nav-icon fa fa-home" aria-hidden="true"></i> <span class="nav-text">Home</span><% end %></li>
          <li class="<%= 'active' if current_page?(categories_path) %>"><%= link_to categories_path do %><i class="nav-icon fa fa-tags" aria-hidden="true"></i> <span class="nav-text">Categories</span><% end %></li>
          
          <% if logged_in? %>
            <li class="<%= 'active' if current_page?(new_post_path) %>"><%= link_to new_post_path do %><i class="nav-icon fa fa-camera-retro" aria-hidden="true"></i> <span class="nav-text">Post</span><% end %></li>
            
            <% if current_user.admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="nav-icon fa fa-unlock" aria-hidden="true"></i> <span class="nav-text">Admin <b class="caret"></b></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
              </ul>
            </li>
            <% end %>

            <li class="dropdown <%= 'active' if current_page?(current_user) || current_page?(edit_user_path(current_user)) %>">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="nav-icon fa fa-user" aria-hidden="true"></i> <span class="nav-text"><%= current_user.username %> <b class="caret"></b></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>
            <li class="<%= 'active' if current_page?(login_path) %>"><%= link_to login_path do %><i class="nav-icon fa fa-sign-in" aria-hidden="true"></i> <span class="nav-text">Sign in</span><% end %></li>
            <li class="<%= 'active' if current_page?(signup_path) %>"><%= link_to signup_path do %><i class="nav-icon fa fa-pencil-square-o" aria-hidden="true"></i> <span class="nav-text">Sign up</span><% end %></li>          
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="<%= yield(:meta_description) %>" />
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    	<%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>